- name:  Install Splunk Universal Forwarder on Windows
  hosts: "all"
  gather_facts: false
  tasks:
  - name: Download earthrise.jpg to specified path through a proxy server.
    win_get_url:
      url: ftp://gitlab.gquites.local/pub/splunkclient.msi
      dest: C:\tmp\splunkclient.msi
  - name: Run a command under cmd
    win_shell: 'msiexec.exe /i C:\tmp\splunkclient.msi RECEIVING_INDEXER="splunk.gquites.local:9997" DEPLOYMENT_SERVER="splunk.gquites.local:8089" AGREETOLICENSE=yes LAUNCHSPLUNK=1 /quiet'
    args:
      executable: PowerShell.exe
